# Generated by Django 5.1.6 on 2025-02-10 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=2000)),
                ('short_url', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
                'ordering': ['pk'],
            },
        ),
    ]
