# Generated by Django 5.1.6 on 2025-02-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='country',
        ),
        migrations.AlterField(
            model_name='click',
            name='browser',
            field=models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('mobile_safari', 'Mobile Safari'), ('edge', 'Edge'), ('opera', 'Opera'), ('internet_explorer', 'Internet Explorer'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='click',
            name='device',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('pc', 'PC'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='click',
            name='os',
            field=models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOs'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('blackberry_os', 'Blackberry OS'), ('chrome_os', 'Chrome OS'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
