# Generated by Django 5.1.6 on 2025-02-28 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_remove_click_country_alter_click_browser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='URLGroup',
        ),
        migrations.AlterModelOptions(
            name='urlgroup',
            options={'ordering': ['user'], 'verbose_name': 'url group', 'verbose_name_plural': 'url groups'},
        ),
        migrations.AlterModelTable(
            name='urlgroup',
            table='url_groups',
        ),
    ]
