# Generated by Django 5.1.6 on 2025-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_rename_group_urlgroup_alter_urlgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
