# Generated by Django 5.1.6 on 2025-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_planfeature_is_active_alter_planfeature_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the plan in the list.'),
        ),
    ]
