# Generated by Django 5.1.6 on 2025-04-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order'], 'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
        migrations.AddField(
            model_name='feature',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the feature in the plan.'),
        ),
    ]
