# Generated by Django 5.1.6 on 2025-04-15 19:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('security', 'Security'), ('branding', 'Branding'), ('analytics', 'Analytics')], default='branding', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the feature in the plan.')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'db_table': 'features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the plan in the list.')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_annual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('checkout_url', models.URLField(blank=True, help_text='URL where the user completes the purchase (e.g., Stripe, Lemon Squeezy, etc.)', null=True)),
                ('links_per_month', models.PositiveIntegerField(default=0)),
                ('api_links_per_month', models.PositiveIntegerField(default=0)),
                ('link_lifetime', models.CharField(choices=[('infinity', 'Infinity'), ('limited', 'Limited')], default='infinity', max_length=50)),
                ('analytics_duration', models.CharField(choices=[('1 month', '1 Month'), ('1 year', '1 Year'), ('3 years', '3 Years')], default='1 month', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra data for integrations, platform-specific info, or internal use.')),
                ('is_test_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'plan_feature',
                'verbose_name_plural': 'plan_features',
                'db_table': 'plan_features',
                'ordering': ['plan', 'feature'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature')],
            },
        ),
    ]
