# Generated by Django 5.1.6 on 2025-04-16 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan')], max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('variant_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['user'],
            },
        ),
    ]
