# Generated by Django 5.1.6 on 2025-04-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
