# Generated by Django 5.1.6 on 2025-04-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_ends_at_subscription_renews_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active_until',
        ),
    ]
