export const plans = [
  {
    name: "Free",
    price: "$0",
    annual: "Annual fee $0",
    features: {
      "Links per month": "250",
      "API links per month": "150",
      "Link lifespan": "Infinity",
      Analytics: "1 Month",
      "Password protection": true,
      "Privacy settings": true,
      "QR Code": true,
      "No ads": false,
      "Custom alias": false,
      "Custom domain": false,
      "Tracking pixels": false,
      "UTM parameters": false,
      "Link groups": false,
      "Link metadata": false,
      "Edit URL": false,
    },
  },
  {
    name: "Basic",
    price: "$4",
    annual: "Annual fee $50",
    popular: true,
    features: {
      "Links per month": "Infinity",
      "API links per month": "500",
      "Link lifespan": "Infinity",
      Analytics: "1 Year",
      "Password protection": true,
      "Privacy settings": true,
      "QR Code": true,
      "No ads": true,
      "Custom alias": true,
      "Custom domain": "1",
      "Tracking pixels": true,
      "UTM parameters": true,
      "Link groups": true,
      "Link metadata": true,
      "Edit URL": true,
    },
  },
  {
    name: "Premium",
    price: "$12",
    annual: "Annual fee $150",
    features: {
      "Links per month": "Infinity",
      "API links per month": "Infinity",
      "Link lifespan": "Infinity",
      Analytics: "3 Years",
      "Password protection": true,
      "Privacy settings": true,
      "QR Code": true,
      "No ads": true,
      "Custom alias": true,
      "Custom domain": "3",
      "Tracking pixels": true,
      "UTM parameters": true,
      "Link groups": true,
      "Link metadata": true,
      "Edit URL": true,
    },
  },
];
