# Generated by Django 5.1.6 on 2025-04-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
