# Generated by Django 5.1.6 on 2026-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_alter_domain_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.URLField(unique=True),
        ),
    ]
